### ISSUE TITLE
Blink commands incorrect

### ISSUE THREAD

**Issue by Eleengineer** [AutomationDirect/ProductivityBlocks#2]
Blink function uses '32' instead of the specified PIN when setting LOW value. This condition does not seem to be restrained to pin D12. 
![Screen Shot 2020-02-21 at 11 19 39 AM](https://user-images.githubusercontent.com/61326147/75056495-bebe5f00-549c-11ea-8365-2963dc1560fd.png)

**Comment by AutomationDirect** [comment]
Thank you for finding and reporting this! It is a small (one-line) fix that is resolved in the next build.

**Comment by AutomationDirect** [comment]
Fixed in 1.0.0.18.
